Add build, test and publish with maven reusable/shared github workflows
mekomsolutions/shared-github-workflow pull request #10
Opened 2024-01-22 09:06 UTC by corneliouzbett

Issue: https://mekomsolutions.atlassian.net/jira/software/c/projects/OZ/issues/OZ-438

This PR adds reusable/shared GitHub workflows.
For now, I've kept the existing workflows as they are not to break dependent workflows. This will allow us to update the existing workflows gradually, and then depreciate the two workflows; `build-publish-workflow.yml` and `validate-workflow.yml`

@rbuisson can you rename the repository to `shared-github-workflow`?

2024-01-22 16:59 UTC, rbuisson commented
@corneliouzbett , done.

2024-01-22 17:09 UTC, rbuisson requested changes
I'm proposing some sort of naming convention.
`<tech>-<operation>.yml`
or
`<tech>/<operation>.yml`

 What do you think?

2024-01-22 17:09 UTC, rbuisson commented on .github/workflows/maven.yml
Not sure if `maven.yml` is the most relevant name here. Eg, why name this `maven.yml` and the other `publish.yml`, even though they are both doing Maven operations.

Would it be possible to group them in folders?
- `.github/workflows/maven/build-test.yml`
- `.github/workflows/maven/publish.yml`

otherwise, name them:
- `maven-build-test.yml`
- `maven-publish.yml`

2024-01-22 17:09 UTC, rbuisson commented on .github/workflows/check-spotless.yml
I would name this one `spotless-check.yml`

2024-01-22 17:09 UTC, rbuisson commented on .github/workflows/notify-ocd3.yml
Well, if we're following the naming convention that I've started to outline in the other comments: `<tech>-<operation>.yml`, then this should be `ocd3-notify.yml`.

2024-01-23 06:45 UTC, corneliouzbett commented
> I'm proposing some sort of naming convention. `<tech>-<operation>.yml` or `<tech>/<operation>.yml`
> 
> What do you think?

`<tech>-<operation>.yml` -  Simple and flat. It's easy to see all workflows at a glance since they are all in the same directory. However, if you have many workflows, this could lead to a cluttered directory.
`<tech>/<operation>.yml` - It is more structured. It groups workflows by technology, which can make it easier to find a specific workflow if you have many. However, it does require navigating through directories.

IMO, let's adopt both, first, let's group by tech, then for cases like `spotless-check` which still runs a maven operation, we do both. e.g.
    
- `.github/workflows/maven/build-test.yml`
- `.github/workflows/maven/publish.yml`
- `.github/workflows/maven/spotless-check.yml`

2024-01-25 06:21 UTC, merged